Allow configuration of Apache HTTP MaxRequestsPerChild and MaxKeepAliveRequests
sclorg/s2i-php-container pull request #326
Opened 2021-03-05 20:43 UTC by jchristi

Apache HTTP configuration values for MaxRequestsPerChild and MaxKeepAliveRequests are hardcoded to 4000 and 100 respectively. My team has a need to significantly lower the MaxRequestsPerChild value to combat memory leakage issues. I made MaxKeepAliveRequests also configurable while I was at it so everything in `50-mpm-tuning.conf` is now configurable via environment variables. The default values have been preserved so there should be zero impact to current users. README files have been updated to add the new config options.

2021-03-08 14:14 UTC, phracek commented on 7.2/s2i/bin/run
> +export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTP_MAX_REQUESTS_PER_CHILD:-4000}
```suggestion
export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTPD_MAX_REQUESTS_PER_CHILD:-4000}
```

2021-03-08 14:14 UTC, phracek commented on 7.3/s2i/bin/run
> +export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTP_MAX_REQUESTS_PER_CHILD:-4000}
```suggestion
export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTPD_MAX_REQUESTS_PER_CHILD:-4000}
```

2021-03-08 14:14 UTC, phracek commented on 7.4/s2i/bin/run
> +export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTP_MAX_REQUESTS_PER_CHILD:-4000}
```suggestion
export HTTPD_MAX_REQUESTS_PER_CHILD=${HTTPD_MAX_REQUESTS_PER_CHILD:-4000}
```

2021-03-08 14:15 UTC, phracek requested changes
Hi jchristi, thanks for the PR! But version 7.2,7.3 and 7.4 are currently only supported. The rest is deprecated. Can you please rebase your PR with only supported versions?

2021-03-08 17:38 UTC, jchristi commented
Done, suggestions applied and removed changes to old php version images.

2021-03-13 13:21 UTC, jchristi commented
The two failing tests seem to be CI infrastructure-related (permissions issues?)

2021-03-16 08:46 UTC, phracek commented
[test-openshift][test]

2021-03-16 09:13 UTC, phracek commented
Issue with OpenShift 3 is here: https://github.com/sclorg/s2i-php-container/issues/328

2021-03-16 09:24 UTC, merged