fix permissions for fpm configuration
sclorg/s2i-php-container pull request #410
Opened 2023-05-11 07:49 UTC by pkubatrh

2023-05-11 07:50 UTC, pkubatrh commented
Follow up for #401 as I missed some fpm configuration in 8.0 and 8.1

2023-05-15 10:39 UTC, phracek commented
The fix is part of #406. Only for info.

2023-05-16 12:20 UTC, phracek requested changes
Everything LGTM. What about adding as well www.conf file like:
`chmod a+rwx ${PHP_FPM_CONF_D_PATH}/${PHP_FPM_CONF_FILE}`
${PHP_SYSCONF_PATH}/php-fpm.d equals to ${PHP_FPM_CONF_D_PATH}.

Can you please modify it?

2023-06-08 07:45 UTC, pkubatrh commented
> What about adding as well [www.conf](http://www.conf/) file like: chmod a+rwx ${PHP_FPM_CONF_D_PATH}/${PHP_FPM_CONF_FILE}

The chmod call is recursive, so that should not be needed. I have modified the original call to use `${PHP_FPM_CONF_D_PATH}` however.

2023-06-08 07:54 UTC, pkubatrh commented
[test]

2023-06-08 11:00 UTC, phracek requested changes
Please address my changes.

2023-06-08 11:08 UTC, phracek commented on 8.0/root/usr/libexec/container-setup
>  if [ "x$PLATFORM" == "xel9" ] || [ "x$PLATFORM" == "xfedora" ]; then
```suggestion
if [ "x$PLATFORM" == "xel9" ] || [ "x$PLATFORM" == "xfedora" ]; then
chmod -R a+rwx "${PHP_SYSCONF_PATH}/php-fpm.d"
```

2023-06-08 11:10 UTC, phracek commented
[test]

2023-06-08 11:54 UTC, phracek approved these changes
LGTM. Thanks for the fix

2023-06-09 06:38 UTC, merged